### ISSUE TITLE
Compile Issues

### ISSUE THREAD

**Issue by Alek20398** [ZeroMemoryEx/U-Boat#1]
Hi, Currently I am using Visual Studio 2022, I'm trying to compile U-boat but I get many errors and no compiled .exe.
I have also used 2019, but same issue. I did try Properties and choosing different platform toolkit, but still not working. If you could let me know the best way to compile properly or command that would be great. Thank you.
![Capture](https://user-images.githubusercontent.com/125716818/221375230-6581d572-3bbf-41fd-9ca6-3cbe34dec2c6.PNG)

**Comment by ZeroMemoryEx** [comment]
compile it in x86
